-- ---------------------------------------------------------------------------------------------
-- DA0.5 -- script 00: read-only catalog check for the mobilisation-radar schema.
--
-- Plan: docs/data-architecture/wp/da0.5.md §3. Migration under comparison:
-- supabase/migrations/20260922040000_mobilisation_radar.sql (766 lines, merged at afc3eed8).
--
-- READ-ONLY. No BEGIN, no environment guard, no writes. Safe on production, the clone and dev.
-- Run as postgres in the SQL editor, or through the connector. The SQL editor returns only the
-- LAST statement's result set per submission, so submit each lettered block ON ITS OWN and paste
-- its output into the plan file (§9 Verification record).
--
-- Blocks A-J prove the sixteen tables in the target database against the migration file
-- (§3 of the plan: object -> in file? -> in production? -> identical?).
-- Blocks K-N are the employer-register reconciliation (§4 of the plan, names only, no PII).
-- Block O is the ledger state the run sheet 10 changes.
--
-- The sixteen tables are named once, in the array below; every block reuses the same list.
-- ---------------------------------------------------------------------------------------------

-- ##########################################  BLOCK A  ################################################
-- Table presence, RLS flag and table comment. Expected: 16 rows, rls_enabled = t on all 16,
-- comments on exactly five (vessels, geofences, mobilisation_signals, mobilisation_alert_events,
-- mobilisation_positions).
SELECT c.relname                                   AS table_name,
       c.relrowsecurity                            AS rls_enabled,
       c.relforcerowsecurity                       AS rls_forced,
       obj_description(c.oid, 'pg_class')          AS table_comment
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
WHERE c.relkind = 'r'
  AND c.relname = ANY (ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ])
ORDER BY c.relname;
-- ########################################  END OF BLOCK A  ###########################################

-- ##########################################  BLOCK B  ################################################
-- Columns: name, ordinal, type, nullability, default, identity. Expected: 171 rows
-- (vessels 23, geofences 9, watch_contractors 10, watch_vessels 5, watch_keywords 6, sources 10,
--  rules 9, signals 26, alerts 21, alert_signals 3, alert_events 8, notifications 9, prefs 7,
--  push_subscriptions 6, positions 11, settings 8). identity = 'd' (GENERATED BY DEFAULT) on the
-- twelve identity keys; '' on mobilisation_sources.source_key, mobilisation_prefs.user_id,
-- mobilisation_settings.id and mobilisation_alert_signals' composite key.
SELECT c.relname                                            AS table_name,
       a.attnum                                             AS ordinal,
       a.attname                                            AS column_name,
       format_type(a.atttypid, a.atttypmod)                 AS data_type,
       a.attnotnull                                         AS not_null,
       pg_get_expr(d.adbin, d.adrelid)                      AS column_default,
       a.attidentity                                        AS identity
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
WHERE c.relname = ANY (ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ])
ORDER BY c.relname, a.attnum;
-- ########################################  END OF BLOCK B  ###########################################

-- ##########################################  BLOCK C  ################################################
-- Constraints with their full definitions (PRIMARY KEY, UNIQUE, CHECK, FOREIGN KEY incl. ON DELETE).
-- Expected: 72 rows -- 16 primary keys, 13 uniques, 20 checks, 23 foreign keys.
SELECT c.relname                         AS table_name,
       con.conname                       AS constraint_name,
       CASE con.contype WHEN 'p' THEN 'PRIMARY KEY' WHEN 'u' THEN 'UNIQUE'
                        WHEN 'c' THEN 'CHECK'       WHEN 'f' THEN 'FOREIGN KEY'
                        ELSE con.contype::text END AS kind,
       pg_get_constraintdef(con.oid)     AS definition
FROM pg_constraint con
JOIN pg_class c ON c.oid = con.conrelid
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
WHERE c.relname = ANY (ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ])
ORDER BY c.relname, con.contype, con.conname;
-- ########################################  END OF BLOCK C  ###########################################

-- ##########################################  BLOCK D  ################################################
-- Indexes. Expected: 33 rows -- 29 backing a PK or UNIQUE constraint (block C: 16 + 13) and the four the
-- migration creates explicitly on mobilisation_signals:
--   idx_mobilisation_signals_occurred, _watch, _vessel, _layer.
SELECT tablename AS table_name, indexname AS index_name, indexdef AS definition
FROM pg_indexes
WHERE schemaname = 'public'
  AND tablename = ANY (ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ])
ORDER BY tablename, indexname;
-- ########################################  END OF BLOCK D  ###########################################

-- ##########################################  BLOCK E  ################################################
-- RLS policies. Expected: 27 rows, every one TO authenticated, PERMISSIVE.
SELECT tablename AS table_name, policyname AS policy_name, permissive, roles::text AS roles,
       cmd, qual AS using_expr, with_check AS check_expr
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename = ANY (ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ])
ORDER BY tablename, policyname;
-- ########################################  END OF BLOCK E  ###########################################

-- ##########################################  BLOCK F  ################################################
-- Triggers. Expected: 8 rows -- seven BEFORE UPDATE ... update_updated_at() (vessels, geofences,
-- watch_contractors, rules, alerts, prefs, settings) and trg_mobilisation_alert_audit
-- (AFTER UPDATE ON mobilisation_alerts).
SELECT c.relname AS table_name, t.tgname AS trigger_name, pg_get_triggerdef(t.oid) AS definition
FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
WHERE NOT t.tgisinternal
  AND c.relname = ANY (ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ])
ORDER BY c.relname, t.tgname;
-- ########################################  END OF BLOCK F  ###########################################

-- ##########################################  BLOCK G  ################################################
-- Functions. mobilisation_alert_audit is the only one the migration creates; update_updated_at and
-- get_user_role are baseline prerequisites it calls (20260908050000_baseline_schema.sql).
-- Expected md5 of pg_get_functiondef on production, 2026-09-22:
--   mobilisation_alert_audit  764235c6343f9cc8189502ba271571e5
--   update_updated_at         28c4c04688c55a53cda7430cc3b538ed
--   get_user_role             286b2eb565b18a700b6867b6dbcd51f5
SELECT p.proname                          AS function_name,
       pg_get_function_identity_arguments(p.oid) AS args,
       l.lanname                          AS language,
       p.prosecdef                        AS security_definer,
       md5(pg_get_functiondef(p.oid))     AS definition_md5,
       pg_get_functiondef(p.oid)          AS definition
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace AND n.nspname = 'public'
JOIN pg_language l ON l.oid = p.prolang
WHERE p.proname IN ('mobilisation_alert_audit', 'update_updated_at', 'get_user_role')
ORDER BY p.proname;
-- ########################################  END OF BLOCK G  ###########################################

-- ##########################################  BLOCK H  ################################################
-- Table grants for the PostgREST roles. Expected on a Supabase project: anon returns NO rows on any
-- of the sixteen (the migration's REVOKE ALL ... FROM PUBLIC, anon), while authenticated and
-- service_role each show the full privilege set on all sixteen -- because Supabase's default
-- privileges (pg_default_acl, public schema) grant ALL on new tables to anon, authenticated and
-- service_role at CREATE TABLE time, and the migration revokes only from PUBLIC and anon. The
-- migration's explicit per-table GRANT SELECT / INSERT / UPDATE / DELETE lines are therefore a
-- floor, not a ceiling: RLS is what actually gates authenticated. See the plan's §3 note.
SELECT table_name, grantee,
       string_agg(privilege_type, ',' ORDER BY privilege_type) AS privileges
FROM information_schema.role_table_grants
WHERE table_schema = 'public'
  AND grantee IN ('anon', 'authenticated', 'service_role', 'PUBLIC')
  AND table_name = ANY (ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ])
GROUP BY table_name, grantee
ORDER BY table_name, grantee;
-- ########################################  END OF BLOCK H  ###########################################

-- ##########################################  BLOCK I  ################################################
-- Identity sequences and their privileges. Expected: 12 rows (one per identity column in the
-- migration's final DO block), owner postgres, USAGE true for authenticated and service_role.
SELECT c.relname                                                            AS sequence_name,
       pg_get_userbyid(c.relowner)                                          AS owner,
       has_sequence_privilege('authenticated', 'public.' || c.relname, 'USAGE') AS authenticated_usage,
       has_sequence_privilege('service_role',  'public.' || c.relname, 'USAGE') AS service_role_usage,
       has_sequence_privilege('anon',          'public.' || c.relname, 'USAGE') AS anon_usage
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
WHERE c.relkind = 'S'
  AND c.relname = ANY (ARRAY[
    'vessels_vessel_id_seq', 'geofences_geofence_id_seq',
    'mobilisation_watch_contractors_watch_id_seq',
    'mobilisation_watch_vessels_watch_vessel_id_seq',
    'mobilisation_watch_keywords_keyword_id_seq', 'mobilisation_rules_rule_id_seq',
    'mobilisation_signals_signal_id_seq', 'mobilisation_alerts_alert_id_seq',
    'mobilisation_alert_events_event_id_seq',
    'mobilisation_notifications_notification_id_seq',
    'mobilisation_push_subscriptions_subscription_id_seq',
    'mobilisation_positions_position_id_seq'
  ])
ORDER BY c.relname;
-- ########################################  END OF BLOCK I  ###########################################

-- ##########################################  BLOCK J  ################################################
-- Row counts, including the seed sets the migration inserts. On a database where the migration has
-- just been applied and nothing else has run, expect exactly:
--   geofences 3, mobilisation_watch_contractors 14, vessels 25, mobilisation_watch_vessels 25,
--   mobilisation_watch_keywords 21, mobilisation_sources 8, mobilisation_rules 4,
--   mobilisation_settings 1, and 0 in the eight event tables.
-- Production on 2026-09-22 additionally held signals 19, alerts 18, alert_signals 18 (live data).
SELECT 'vessels' AS table_name, count(*) AS rows FROM public.vessels
UNION ALL SELECT 'geofences', count(*) FROM public.geofences
UNION ALL SELECT 'mobilisation_watch_contractors', count(*) FROM public.mobilisation_watch_contractors
UNION ALL SELECT 'mobilisation_watch_vessels', count(*) FROM public.mobilisation_watch_vessels
UNION ALL SELECT 'mobilisation_watch_keywords', count(*) FROM public.mobilisation_watch_keywords
UNION ALL SELECT 'mobilisation_sources', count(*) FROM public.mobilisation_sources
UNION ALL SELECT 'mobilisation_rules', count(*) FROM public.mobilisation_rules
UNION ALL SELECT 'mobilisation_signals', count(*) FROM public.mobilisation_signals
UNION ALL SELECT 'mobilisation_alerts', count(*) FROM public.mobilisation_alerts
UNION ALL SELECT 'mobilisation_alert_signals', count(*) FROM public.mobilisation_alert_signals
UNION ALL SELECT 'mobilisation_alert_events', count(*) FROM public.mobilisation_alert_events
UNION ALL SELECT 'mobilisation_notifications', count(*) FROM public.mobilisation_notifications
UNION ALL SELECT 'mobilisation_prefs', count(*) FROM public.mobilisation_prefs
UNION ALL SELECT 'mobilisation_push_subscriptions', count(*) FROM public.mobilisation_push_subscriptions
UNION ALL SELECT 'mobilisation_positions', count(*) FROM public.mobilisation_positions
UNION ALL SELECT 'mobilisation_settings', count(*) FROM public.mobilisation_settings
ORDER BY 1;
-- ########################################  END OF BLOCK J  ###########################################

-- ##########################################  BLOCK K  ################################################
-- RECONCILIATION 1 (plan §4): every vessel against the employer register. Organisation names only.
-- link_state:
--   'unlinked'          owner_operator_id IS NULL
--   'exact'             the linked employer's name equals owner_name (case-insensitive)
--   'name_mismatch'     linked, but the employer's name is not the owner name -- adjudicate
--   'dangling'          owner_operator_id set but no employers row (impossible under the FK)
--   'synthetic_787_794' linked into the DA0.2 synthetic set -- must be cleared before DA0.2 runs
SELECT v.vessel_id,
       v.name           AS vessel_name,
       v.owner_name,
       v.relevance,
       v.is_active,
       v.owner_operator_id,
       e.employer_name  AS linked_employer_name,
       e.is_active      AS linked_employer_active,
       CASE
         WHEN v.owner_operator_id IS NULL                       THEN 'unlinked'
         WHEN e.employer_id IS NULL                             THEN 'dangling'
         WHEN v.owner_operator_id BETWEEN 787 AND 794           THEN 'synthetic_787_794'
         WHEN lower(e.employer_name) = lower(v.owner_name)      THEN 'exact'
         ELSE 'name_mismatch'
       END              AS link_state
FROM public.vessels v
LEFT JOIN public.employers e ON e.employer_id = v.owner_operator_id
ORDER BY v.vessel_id;
-- ########################################  END OF BLOCK K  ###########################################

-- ##########################################  BLOCK L  ################################################
-- RECONCILIATION 2 (plan §4): every watch contractor against the employer register.
SELECT w.watch_id,
       w.canonical_name,
       w.aliases,
       w.tier,
       w.is_active,
       w.employer_id,
       e.employer_name  AS linked_employer_name,
       e.is_active      AS linked_employer_active,
       CASE
         WHEN w.employer_id IS NULL                              THEN 'unlinked'
         WHEN e.employer_id IS NULL                              THEN 'dangling'
         WHEN w.employer_id BETWEEN 787 AND 794                  THEN 'synthetic_787_794'
         WHEN lower(e.employer_name) = lower(w.canonical_name)   THEN 'exact'
         ELSE 'name_mismatch'
       END              AS link_state
FROM public.mobilisation_watch_contractors w
LEFT JOIN public.employers e ON e.employer_id = w.employer_id
ORDER BY w.watch_id;
-- ########################################  END OF BLOCK L  ###########################################

-- ##########################################  BLOCK M  ################################################
-- RECONCILIATION 3 (plan §4): every alias string in mobilisation_watch_contractors.aliases against
-- employer_name_aliases and employers. in_employer_name_aliases = 0 means the fourth alias store
-- (plan §1.11) disagrees with the register; DA1.4 folds these in.
WITH alias_rows AS (
  SELECT w.watch_id, w.canonical_name, unnest(w.aliases) AS alias_string
  FROM public.mobilisation_watch_contractors w
)
SELECT a.watch_id,
       a.canonical_name,
       a.alias_string,
       (SELECT count(*) FROM public.employer_name_aliases ena
          WHERE lower(ena.alias_name) = lower(a.alias_string))   AS in_employer_name_aliases,
       (SELECT count(*) FROM public.employers e
          WHERE lower(e.employer_name) = lower(a.alias_string))  AS alias_is_an_employer_name,
       (SELECT count(*) FROM public.employers e
          WHERE lower(e.employer_name) = lower(a.canonical_name)) AS canonical_is_an_employer_name
FROM alias_rows a
ORDER BY a.watch_id, a.alias_string;
-- ########################################  END OF BLOCK M  ###########################################

-- ##########################################  BLOCK N  ################################################
-- RECONCILIATION 4 (plan §4): the summary line for the ledger's incidental findings.
SELECT (SELECT count(*) FROM public.vessels)                                            AS vessels_total,
       (SELECT count(*) FROM public.vessels WHERE owner_operator_id IS NOT NULL)        AS vessels_linked,
       (SELECT count(*) FROM public.vessels v JOIN public.employers e
          ON e.employer_id = v.owner_operator_id
         WHERE lower(e.employer_name) <> lower(v.owner_name))                           AS vessels_name_mismatch,
       (SELECT count(*) FROM public.vessels
         WHERE owner_operator_id BETWEEN 787 AND 794)                                   AS vessels_into_synthetic,
       (SELECT count(*) FROM public.mobilisation_watch_contractors)                     AS contractors_total,
       (SELECT count(*) FROM public.mobilisation_watch_contractors
         WHERE employer_id IS NOT NULL)                                                 AS contractors_linked,
       (SELECT count(*) FROM public.mobilisation_watch_contractors w JOIN public.employers e
          ON e.employer_id = w.employer_id
         WHERE lower(e.employer_name) <> lower(w.canonical_name))                       AS contractors_name_mismatch,
       (SELECT count(*) FROM public.mobilisation_watch_contractors
         WHERE employer_id BETWEEN 787 AND 794)                                         AS contractors_into_synthetic,
       (SELECT count(*) FROM (
          SELECT unnest(aliases) AS a FROM public.mobilisation_watch_contractors
        ) x WHERE NOT EXISTS (
          SELECT 1 FROM public.employer_name_aliases ena WHERE lower(ena.alias_name) = lower(x.a)
        ))                                                                              AS alias_strings_missing_from_register;
-- ########################################  END OF BLOCK N  ###########################################

-- ##########################################  BLOCK O  ################################################
-- Ledger state. This is the precondition 10_record_ledger_row.sql asserts and the post-state it
-- leaves. On production before 10: tables_present = 16, ledger_row_present = f, ledger_max_version
-- = '20260921030000'. On the 12 September clone before the migration: tables_present = 0,
-- ledger_row_present = f, ledger_max_version = '20260917100000'.
SELECT (SELECT count(*) FROM pg_class c
         JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
        WHERE c.relkind = 'r' AND c.relname = ANY (ARRAY[
          'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
          'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
          'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
          'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
          'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
        ]))                                                                AS tables_present,
       EXISTS (SELECT 1 FROM supabase_migrations.schema_migrations
                WHERE version = '20260922040000')                          AS ledger_row_present,
       (SELECT max(version) FROM supabase_migrations.schema_migrations)    AS ledger_max_version,
       (SELECT count(*) FROM supabase_migrations.schema_migrations)        AS ledger_rows;
-- ########################################  END OF BLOCK O  ###########################################
