-- Weekly membership files that need an admin's eye before filing.
--
-- The weekly files are no longer recognised by one exact file name: the
-- kind comes from the column layout (with the name as a hint) and the week
-- from a date in the name, read loosely and shared across files sent
-- together. When those signals disagree or are missing — no date, a date
-- that could be read two ways, a name that says "Resigned" on a New Members
-- layout — the file is kept here instead of being dropped, and the Weekly
-- Updates tab asks an admin to confirm the kind and week before it is filed
-- into its batch.
--
-- membership_update_files.classification records how each filed file's kind
-- and week were worked out (from the columns, the name, the other files in
-- the email, or an admin's review).

ALTER TABLE "public"."membership_update_files"
  ADD COLUMN IF NOT EXISTS "classification" jsonb;

COMMENT ON COLUMN "public"."membership_update_files"."classification" IS
  'How the kind and week ending were worked out: notes, signals, and who confirmed it when reviewed.';

CREATE TABLE IF NOT EXISTS "public"."membership_update_review_files" (
  "review_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "filename" text NOT NULL,
  "storage_bucket" text NOT NULL DEFAULT 'membership-updates',
  "storage_path" text NOT NULL,
  "byte_size" bigint,
  "row_count" integer,
  "source" text NOT NULL DEFAULT 'email',
  "source_email_id" text,
  "source_from" text,
  "source_subject" text,
  "resend_attachment_id" text,
  "suggested_kind" text,
  "suggested_week_ending" date,
  "issues" text[] NOT NULL DEFAULT '{}'::text[],
  "classification" jsonb,
  "status" text NOT NULL DEFAULT 'pending',
  "received_at" timestamp with time zone NOT NULL DEFAULT now(),
  "resolved_at" timestamp with time zone,
  "resolved_by" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
  "filed_batch_id" bigint REFERENCES "public"."membership_update_batches"("batch_id") ON DELETE SET NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "membership_update_review_files_status_check"
    CHECK ("status" IN ('pending', 'filed', 'discarded')),
  CONSTRAINT "membership_update_review_files_source_check"
    CHECK ("source" IN ('email', 'manual')),
  CONSTRAINT "membership_update_review_files_kind_check"
    CHECK ("suggested_kind" IS NULL OR "suggested_kind" IN ('new', 'recommenced', 'resigned', 'unfinancial'))
);

ALTER TABLE "public"."membership_update_review_files" OWNER TO "postgres";

COMMENT ON TABLE "public"."membership_update_review_files" IS
  'Weekly membership spreadsheets whose kind or week ending could not be settled automatically, held for an admin to confirm.';

CREATE INDEX IF NOT EXISTS "idx_membership_update_review_files_pending"
  ON "public"."membership_update_review_files" ("received_at" DESC)
  WHERE "status" = 'pending';

-- A re-delivered webhook must not queue the same attachment twice.
CREATE UNIQUE INDEX IF NOT EXISTS "idx_membership_update_review_files_attachment"
  ON "public"."membership_update_review_files" ("resend_attachment_id")
  WHERE "resend_attachment_id" IS NOT NULL;

CREATE OR REPLACE TRIGGER "trg_membership_update_review_files_updated_at"
  BEFORE UPDATE ON "public"."membership_update_review_files"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();

ALTER TABLE "public"."membership_update_review_files" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin read membership_update_review_files" ON "public"."membership_update_review_files";
CREATE POLICY "Admin read membership_update_review_files"
  ON "public"."membership_update_review_files" FOR SELECT TO "authenticated"
  USING ("public"."get_user_role"() = 'admin');

REVOKE ALL ON TABLE "public"."membership_update_review_files" FROM PUBLIC, "anon";
GRANT SELECT ON TABLE "public"."membership_update_review_files" TO "authenticated";
GRANT ALL ON TABLE "public"."membership_update_review_files" TO "service_role";

DO $$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.membership_update_review_files', 'review_id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', seq);
  END IF;
END $$;
