-- Weekly membership updates emailed to the app.
--
-- The membership system emails four spreadsheets every week — New Members,
-- Recommenced Members, Resigned Members and Unfinancial Members — each named
-- "OA - <Kind> Members - w-e DD-MM-YYYY.xlsx". The inbound-email webhook
-- files them here by week-ending date; when all four have arrived the batch
-- is "ready", the selected admins are notified on their next visit, and a
-- point-in-time membership movement record is written so movement over time
-- can be reported. Importing a batch runs the membership import wizard on
-- the combined rows, with the same campaign-protection rule as every other
-- membership import.
--
-- All reads and writes go through API routes (service role after an admin
-- check). Authenticated admins may also read directly; nobody else can.

-- ── Storage ─────────────────────────────────────────────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('membership-updates', 'membership-updates', false, 52428800, NULL)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- No storage.objects policies: the bucket is service-role only. Files are
-- served to admins through the API.

-- ── Batches (one per week-ending date) ──────────────────────────────────────

CREATE TABLE IF NOT EXISTS "public"."membership_update_batches" (
  "batch_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "week_ending" date NOT NULL UNIQUE,
  "status" text NOT NULL DEFAULT 'receiving',
  "source" text NOT NULL DEFAULT 'email',
  "source_email_id" text,
  "source_from" text,
  "source_subject" text,
  "received_at" timestamp with time zone NOT NULL DEFAULT now(),
  "ready_at" timestamp with time zone,
  "imported_at" timestamp with time zone,
  "imported_by" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
  "import_summary" jsonb,
  "dismissed_at" timestamp with time zone,
  "dismissed_by" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "membership_update_batches_status_check"
    CHECK ("status" IN ('receiving', 'ready', 'imported', 'dismissed')),
  CONSTRAINT "membership_update_batches_source_check"
    CHECK ("source" IN ('email', 'manual'))
);

ALTER TABLE "public"."membership_update_batches" OWNER TO "postgres";

COMMENT ON TABLE "public"."membership_update_batches" IS
  'One weekly membership update (the four emailed spreadsheets) keyed by the week-ending date in the file names.';

CREATE OR REPLACE TRIGGER "trg_membership_update_batches_updated_at"
  BEFORE UPDATE ON "public"."membership_update_batches"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();

-- ── Files (one per kind per batch; a re-send replaces) ──────────────────────

CREATE TABLE IF NOT EXISTS "public"."membership_update_files" (
  "file_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_id" bigint NOT NULL REFERENCES "public"."membership_update_batches"("batch_id") ON DELETE CASCADE,
  "kind" text NOT NULL,
  "filename" text NOT NULL,
  "storage_bucket" text NOT NULL DEFAULT 'membership-updates',
  "storage_path" text NOT NULL,
  "byte_size" bigint,
  "row_count" integer,
  "resend_attachment_id" text,
  "received_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "membership_update_files_kind_check"
    CHECK ("kind" IN ('new', 'recommenced', 'resigned', 'unfinancial')),
  CONSTRAINT "membership_update_files_batch_kind_key" UNIQUE ("batch_id", "kind")
);

ALTER TABLE "public"."membership_update_files" OWNER TO "postgres";

COMMENT ON TABLE "public"."membership_update_files" IS
  'The spreadsheets received for a weekly membership update, stored in the membership-updates bucket.';

CREATE INDEX IF NOT EXISTS "idx_membership_update_files_batch"
  ON "public"."membership_update_files" ("batch_id");

-- ── Movement snapshots (point in time, dated by week ending) ────────────────

CREATE TABLE IF NOT EXISTS "public"."membership_movement_snapshots" (
  "snapshot_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "as_of" date NOT NULL,
  "source" text NOT NULL DEFAULT 'weekly_update',
  "batch_id" bigint REFERENCES "public"."membership_update_batches"("batch_id") ON DELETE SET NULL,
  "new_members" integer NOT NULL DEFAULT 0,
  "recommenced_members" integer NOT NULL DEFAULT 0,
  "resigned_members" integer NOT NULL DEFAULT 0,
  "unfinancial_members" integer NOT NULL DEFAULT 0,
  -- (new + recommenced) - (resigned + unfinancial)
  "net_movement" integer GENERATED ALWAYS AS (
    ("new_members" + "recommenced_members") - ("resigned_members" + "unfinancial_members")
  ) STORED,
  "tags" text[] NOT NULL DEFAULT '{}'::text[],
  "notes" text,
  "created_by" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "membership_movement_snapshots_as_of_source_key" UNIQUE ("as_of", "source"),
  CONSTRAINT "membership_movement_snapshots_counts_check" CHECK (
    "new_members" >= 0 AND "recommenced_members" >= 0
    AND "resigned_members" >= 0 AND "unfinancial_members" >= 0
  )
);

ALTER TABLE "public"."membership_movement_snapshots" OWNER TO "postgres";

COMMENT ON TABLE "public"."membership_movement_snapshots" IS
  'Dated membership movement: counts from each weekly file and the net (new + recommenced) - (resigned + unfinancial).';

CREATE INDEX IF NOT EXISTS "idx_membership_movement_snapshots_as_of"
  ON "public"."membership_movement_snapshots" ("as_of" DESC);

CREATE OR REPLACE TRIGGER "trg_membership_movement_snapshots_updated_at"
  BEFORE UPDATE ON "public"."membership_movement_snapshots"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();

-- ── Notifications (per recipient per batch) ─────────────────────────────────

CREATE TABLE IF NOT EXISTS "public"."membership_update_notifications" (
  "notification_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_id" bigint NOT NULL REFERENCES "public"."membership_update_batches"("batch_id") ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "seen_at" timestamp with time zone,
  "dismissed_at" timestamp with time zone,
  CONSTRAINT "membership_update_notifications_batch_user_key" UNIQUE ("batch_id", "user_id")
);

ALTER TABLE "public"."membership_update_notifications" OWNER TO "postgres";

COMMENT ON TABLE "public"."membership_update_notifications" IS
  'Admins to tell, on their next visit, that a weekly membership update is ready to import.';

CREATE INDEX IF NOT EXISTS "idx_membership_update_notifications_user_open"
  ON "public"."membership_update_notifications" ("user_id")
  WHERE "dismissed_at" IS NULL;

-- ── Row level security ──────────────────────────────────────────────────────

ALTER TABLE "public"."membership_update_batches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."membership_update_files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."membership_movement_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."membership_update_notifications" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin read membership_update_batches" ON "public"."membership_update_batches";
CREATE POLICY "Admin read membership_update_batches"
  ON "public"."membership_update_batches" FOR SELECT TO "authenticated"
  USING ("public"."get_user_role"() = 'admin');

DROP POLICY IF EXISTS "Admin read membership_update_files" ON "public"."membership_update_files";
CREATE POLICY "Admin read membership_update_files"
  ON "public"."membership_update_files" FOR SELECT TO "authenticated"
  USING ("public"."get_user_role"() = 'admin');

DROP POLICY IF EXISTS "Admin read membership_movement_snapshots" ON "public"."membership_movement_snapshots";
CREATE POLICY "Admin read membership_movement_snapshots"
  ON "public"."membership_movement_snapshots" FOR SELECT TO "authenticated"
  USING ("public"."get_user_role"() = 'admin');

DROP POLICY IF EXISTS "Own membership_update_notifications" ON "public"."membership_update_notifications";
CREATE POLICY "Own membership_update_notifications"
  ON "public"."membership_update_notifications" FOR SELECT TO "authenticated"
  USING ("user_id" = auth.uid());

REVOKE ALL ON TABLE "public"."membership_update_batches" FROM PUBLIC, "anon";
REVOKE ALL ON TABLE "public"."membership_update_files" FROM PUBLIC, "anon";
REVOKE ALL ON TABLE "public"."membership_movement_snapshots" FROM PUBLIC, "anon";
REVOKE ALL ON TABLE "public"."membership_update_notifications" FROM PUBLIC, "anon";

GRANT SELECT ON TABLE "public"."membership_update_batches" TO "authenticated";
GRANT SELECT ON TABLE "public"."membership_update_files" TO "authenticated";
GRANT SELECT ON TABLE "public"."membership_movement_snapshots" TO "authenticated";
GRANT SELECT ON TABLE "public"."membership_update_notifications" TO "authenticated";

GRANT ALL ON TABLE "public"."membership_update_batches" TO "service_role";
GRANT ALL ON TABLE "public"."membership_update_files" TO "service_role";
GRANT ALL ON TABLE "public"."membership_movement_snapshots" TO "service_role";
GRANT ALL ON TABLE "public"."membership_update_notifications" TO "service_role";

DO $$
DECLARE
  t text;
  seq text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'public.membership_update_batches:batch_id',
    'public.membership_update_files:file_id',
    'public.membership_movement_snapshots:snapshot_id',
    'public.membership_update_notifications:notification_id'
  ] LOOP
    seq := pg_get_serial_sequence(split_part(t, ':', 1), split_part(t, ':', 2));
    IF seq IS NOT NULL THEN
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', seq);
    END IF;
  END LOOP;
END $$;

-- ── Settings ────────────────────────────────────────────────────────────────

-- Comma-separated auth user ids of the admins to notify. Empty = every admin.
INSERT INTO "public"."app_settings" ("key", "value")
VALUES ('membership_update_notify_user_ids', '')
ON CONFLICT ("key") DO NOTHING;
