-- Draft-level file attachments for outbound campaign emails.
--
-- Inbox replies already store files on email_message_attachments. Campaign
-- sends (Outlook and the SendGrid queue) had no place to keep a PDF or
-- other document with the draft, so every recipient went out without one.
-- Rows here are the files the composer attaches to a campaign_comms_drafts
-- email. Storage objects live in the existing private email-attachments
-- bucket under drafts/{campaign_id}/{draft_id}/ so a later send can load
-- the same bytes for every recipient.
--
-- Writes go through the API (service role) after a campaign write check.
-- Authenticated staff can read metadata, and can upload or delete only
-- objects under the drafts/ prefix — the same admin/user gate as
-- campaign-documents. Direct upload avoids the platform request-body cap
-- on multi-megabyte PDFs.

CREATE TABLE IF NOT EXISTS "public"."email_draft_attachments" (
  "attachment_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "draft_id" integer NOT NULL REFERENCES "public"."campaign_comms_drafts"("draft_id") ON DELETE CASCADE,
  "campaign_id" integer NOT NULL REFERENCES "public"."campaigns"("campaign_id") ON DELETE CASCADE,
  "storage_bucket" text NOT NULL DEFAULT 'email-attachments',
  "storage_path" text NOT NULL,
  "filename" text NOT NULL,
  "content_type" text,
  "byte_size" bigint NOT NULL,
  "source_document_id" integer REFERENCES "public"."documents"("document_id") ON DELETE SET NULL,
  "created_by" uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "email_draft_attachments_byte_size_check" CHECK ("byte_size" > 0),
  CONSTRAINT "email_draft_attachments_filename_check" CHECK (
    char_length("filename") BETWEEN 1 AND 180
    AND "filename" !~ '[\\/]'
  ),
  CONSTRAINT "email_draft_attachments_storage_path_check" CHECK (
    "storage_path" ~ '^drafts/[0-9]+/[0-9]+/[^/]+$'
    AND "storage_bucket" = 'email-attachments'
  )
);

ALTER TABLE "public"."email_draft_attachments" OWNER TO "postgres";

COMMENT ON TABLE "public"."email_draft_attachments" IS
  'PDF and document files attached to an outbound campaign email draft. Copied onto each Outlook or platform send.';

CREATE INDEX IF NOT EXISTS "idx_email_draft_attachments_draft"
  ON "public"."email_draft_attachments" ("draft_id", "attachment_id");

ALTER TABLE "public"."email_draft_attachments" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated read email draft attachments"
  ON "public"."email_draft_attachments";
CREATE POLICY "Authenticated read email draft attachments"
  ON "public"."email_draft_attachments"
  FOR SELECT TO "authenticated"
  USING (true);

REVOKE ALL ON TABLE "public"."email_draft_attachments" FROM PUBLIC;
REVOKE ALL ON TABLE "public"."email_draft_attachments" FROM "anon";
GRANT SELECT ON TABLE "public"."email_draft_attachments" TO "authenticated";
GRANT ALL ON TABLE "public"."email_draft_attachments" TO "service_role";

DO $$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.email_draft_attachments', 'attachment_id');
  IF seq IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', seq);
  END IF;
END $$;

DROP POLICY IF EXISTS "Staff upload draft email attachments"
  ON storage.objects;
CREATE POLICY "Staff upload draft email attachments"
  ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'email-attachments'
    AND name LIKE 'drafts/%'
    AND public.get_user_role() = ANY (ARRAY['admin'::text, 'user'::text])
  );

DROP POLICY IF EXISTS "Staff delete draft email attachments"
  ON storage.objects;
CREATE POLICY "Staff delete draft email attachments"
  ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'email-attachments'
    AND name LIKE 'drafts/%'
    AND public.get_user_role() = ANY (ARRAY['admin'::text, 'user'::text])
  );
