-- Mobilisation radar: vessels, geofences, fused signals, watchlist, alerts.
--
-- Contractors and operators are existing employers rows. Signals store the
-- employer id when a name resolves, and always store the watchlist row so
-- fusion still works before that link is confirmed. AIS positions are for
-- internal display and alerting only — commercial AIS licences prohibit
-- redistribution, so this table is not exposed to anon and rows older than
-- the poller's retention window are deleted.

CREATE TABLE IF NOT EXISTS "public"."vessels" (
  "vessel_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imo" character varying(7),
  "mmsi" character varying(9),
  "name" character varying(200) NOT NULL,
  "vessel_type" character varying(30) NOT NULL DEFAULT 'other',
  "owner_name" character varying(200) NOT NULL,
  "owner_operator_id" integer,
  "relevance" character varying(20) NOT NULL DEFAULT 'nw',
  "notes" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "resolution_note" text,
  "last_lat" numeric(9,6),
  "last_lng" numeric(9,6),
  "last_sog_kn" numeric(6,2),
  "last_cog_deg" numeric(6,2),
  "last_destination" text,
  "last_eta" timestamp with time zone,
  "last_position_at" timestamp with time zone,
  "last_position_source" text,
  "inside_geofence_ids" integer[] NOT NULL DEFAULT '{}',
  "next_poll_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "vessels_imo_unique" UNIQUE ("imo"),
  CONSTRAINT "vessels_name_owner_unique" UNIQUE ("name", "owner_name"),
  CONSTRAINT "vessels_type_check" CHECK (
    "vessel_type" IN (
      'pipelay', 'heavy_lift', 'dsv', 'survey', 'usv',
      'rock_install', 'dredger', 'fpso', 'construction', 'other'
    )
  ),
  CONSTRAINT "vessels_relevance_check" CHECK ("relevance" IN ('nw', 'global', 'low')),
  CONSTRAINT "vessels_imo_format_check" CHECK ("imo" IS NULL OR "imo" ~ '^[0-9]{7}$'),
  CONSTRAINT "vessels_owner_operator_id_fkey"
    FOREIGN KEY ("owner_operator_id") REFERENCES "public"."employers"("employer_id") ON DELETE SET NULL
);

COMMENT ON TABLE "public"."vessels" IS
  'Marine and subsea vessels on the mobilisation watch. IMO is the stable key; MMSI can change with flag.';

CREATE TABLE IF NOT EXISTS "public"."geofences" (
  "geofence_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" character varying(200) NOT NULL,
  "slug" character varying(80) NOT NULL,
  "description" text,
  "geometry" jsonb NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_by" uuid,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "geofences_slug_unique" UNIQUE ("slug"),
  CONSTRAINT "geofences_geometry_type_check" CHECK (
    ("geometry"->>'type') IN ('Polygon', 'MultiPolygon')
  )
);

COMMENT ON TABLE "public"."geofences" IS
  'Editable region polygons. Seeded rings cover the NW Shelf, Browse and Bonaparte / Timor Sea and exclude Bass Strait.';

CREATE TABLE IF NOT EXISTS "public"."mobilisation_watch_contractors" (
  "watch_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "canonical_name" character varying(200) NOT NULL,
  "aliases" text[] NOT NULL DEFAULT '{}',
  "employer_id" integer,
  "asx_ticker" character varying(12),
  "tier" character varying(20) NOT NULL DEFAULT 'core',
  "is_active" boolean NOT NULL DEFAULT true,
  "notes" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_watch_contractors_name_unique" UNIQUE ("canonical_name"),
  CONSTRAINT "mobilisation_watch_contractors_tier_check" CHECK ("tier" IN ('core', 'adjacent')),
  CONSTRAINT "mobilisation_watch_contractors_employer_id_fkey"
    FOREIGN KEY ("employer_id") REFERENCES "public"."employers"("employer_id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_watch_vessels" (
  "watch_vessel_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vessel_id" integer NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "notes" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_watch_vessels_vessel_unique" UNIQUE ("vessel_id"),
  CONSTRAINT "mobilisation_watch_vessels_vessel_id_fkey"
    FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vessel_id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_watch_keywords" (
  "keyword_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "keyword" character varying(200) NOT NULL,
  "kind" character varying(20) NOT NULL,
  "asx_ticker" character varying(12),
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_watch_keywords_unique" UNIQUE ("keyword", "kind"),
  CONSTRAINT "mobilisation_watch_keywords_kind_check" CHECK (
    "kind" IN ('region', 'operator', 'project', 'general')
  )
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_sources" (
  "source_key" text PRIMARY KEY,
  "layer" text NOT NULL,
  "display_name" text NOT NULL,
  "poll_interval_minutes" integer NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "config" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "cursor" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_polled_at" timestamp with time zone,
  "last_success_at" timestamp with time zone,
  "last_error" text,
  CONSTRAINT "mobilisation_sources_layer_check" CHECK ("layer" IN ('regulatory', 'commercial', 'ais')),
  CONSTRAINT "mobilisation_sources_interval_check" CHECK ("poll_interval_minutes" BETWEEN 5 AND 10080)
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_rules" (
  "rule_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "enabled" boolean NOT NULL DEFAULT true,
  "priority" text NOT NULL,
  "config" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_rules_code_unique" UNIQUE ("code"),
  CONSTRAINT "mobilisation_rules_priority_check" CHECK ("priority" IN ('low', 'normal', 'high', 'critical'))
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_signals" (
  "signal_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_layer" text NOT NULL,
  "source" text NOT NULL,
  "source_key" text,
  "signal_type" text NOT NULL,
  "occurred_at" timestamp with time zone NOT NULL,
  "detected_at" timestamp with time zone NOT NULL DEFAULT now(),
  "title" text NOT NULL,
  "extract" text,
  "url" text,
  "confidence" numeric(4,3) NOT NULL,
  "in_region" boolean NOT NULL DEFAULT true,
  "vessel_id" integer,
  "contractor_id" integer,
  "watch_contractor_id" integer,
  "operator_id" integer,
  "worksite_id" integer,
  "geofence_id" integer,
  "sector_id" integer,
  "region_label" text,
  "dedup_key" text NOT NULL,
  "fingerprint" text NOT NULL,
  "external_id" text,
  "matched_terms" text[] NOT NULL DEFAULT '{}',
  "also_seen" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_signals_dedup_unique" UNIQUE ("dedup_key"),
  CONSTRAINT "mobilisation_signals_fingerprint_unique" UNIQUE ("fingerprint"),
  CONSTRAINT "mobilisation_signals_layer_check" CHECK ("source_layer" IN ('regulatory', 'commercial', 'ais')),
  CONSTRAINT "mobilisation_signals_type_check" CHECK (
    "signal_type" IN (
      'ep_lodged', 'ep_varied', 'ep_accepted', 'activity_notification', 'enforcement',
      'award', 'news', 'vessel_area_entry', 'vessel_area_exit', 'vessel_course_toward'
    )
  ),
  CONSTRAINT "mobilisation_signals_confidence_check" CHECK ("confidence" >= 0 AND "confidence" <= 1),
  CONSTRAINT "mobilisation_signals_vessel_id_fkey"
    FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vessel_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_signals_contractor_id_fkey"
    FOREIGN KEY ("contractor_id") REFERENCES "public"."employers"("employer_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_signals_watch_contractor_id_fkey"
    FOREIGN KEY ("watch_contractor_id") REFERENCES "public"."mobilisation_watch_contractors"("watch_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_signals_operator_id_fkey"
    FOREIGN KEY ("operator_id") REFERENCES "public"."employers"("employer_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_signals_worksite_id_fkey"
    FOREIGN KEY ("worksite_id") REFERENCES "public"."worksites"("worksite_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_signals_geofence_id_fkey"
    FOREIGN KEY ("geofence_id") REFERENCES "public"."geofences"("geofence_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_signals_sector_id_fkey"
    FOREIGN KEY ("sector_id") REFERENCES "public"."sectors"("sector_id") ON DELETE SET NULL
);

COMMENT ON TABLE "public"."mobilisation_signals" IS
  'Unified early-warning stream. One row per event after cross-source dedup. AIS rows confirm timing; they are not the sole trigger.';

CREATE INDEX IF NOT EXISTS "idx_mobilisation_signals_occurred"
  ON "public"."mobilisation_signals" ("occurred_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_mobilisation_signals_watch"
  ON "public"."mobilisation_signals" ("watch_contractor_id", "occurred_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_mobilisation_signals_vessel"
  ON "public"."mobilisation_signals" ("vessel_id", "occurred_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_mobilisation_signals_layer"
  ON "public"."mobilisation_signals" ("source_layer", "in_region");

CREATE TABLE IF NOT EXISTS "public"."mobilisation_alerts" (
  "alert_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rule_id" integer NOT NULL,
  "dedup_key" text NOT NULL,
  "status" text NOT NULL DEFAULT 'new',
  "priority" text NOT NULL,
  "title" text NOT NULL,
  "summary" text NOT NULL,
  "confidence" numeric(4,3) NOT NULL,
  "contractor_id" integer,
  "watch_contractor_id" integer,
  "vessel_id" integer,
  "operator_id" integer,
  "worksite_id" integer,
  "snoozed_until" timestamp with time zone,
  "status_note" text,
  "acknowledged_by" uuid,
  "acknowledged_at" timestamp with time zone,
  "dismissed_by" uuid,
  "dismissed_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_alerts_dedup_unique" UNIQUE ("dedup_key"),
  CONSTRAINT "mobilisation_alerts_status_check" CHECK ("status" IN ('new', 'acknowledged', 'snoozed', 'dismissed')),
  CONSTRAINT "mobilisation_alerts_priority_check" CHECK ("priority" IN ('low', 'normal', 'high', 'critical')),
  CONSTRAINT "mobilisation_alerts_rule_id_fkey"
    FOREIGN KEY ("rule_id") REFERENCES "public"."mobilisation_rules"("rule_id"),
  CONSTRAINT "mobilisation_alerts_contractor_id_fkey"
    FOREIGN KEY ("contractor_id") REFERENCES "public"."employers"("employer_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_alerts_watch_contractor_id_fkey"
    FOREIGN KEY ("watch_contractor_id") REFERENCES "public"."mobilisation_watch_contractors"("watch_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_alerts_vessel_id_fkey"
    FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vessel_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_alerts_operator_id_fkey"
    FOREIGN KEY ("operator_id") REFERENCES "public"."employers"("employer_id") ON DELETE SET NULL,
  CONSTRAINT "mobilisation_alerts_worksite_id_fkey"
    FOREIGN KEY ("worksite_id") REFERENCES "public"."worksites"("worksite_id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_alert_signals" (
  "alert_id" bigint NOT NULL,
  "signal_id" bigint NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("alert_id", "signal_id"),
  CONSTRAINT "mobilisation_alert_signals_alert_id_fkey"
    FOREIGN KEY ("alert_id") REFERENCES "public"."mobilisation_alerts"("alert_id") ON DELETE CASCADE,
  CONSTRAINT "mobilisation_alert_signals_signal_id_fkey"
    FOREIGN KEY ("signal_id") REFERENCES "public"."mobilisation_signals"("signal_id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_alert_events" (
  "event_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "alert_id" bigint NOT NULL,
  "actor_id" uuid,
  "action" text NOT NULL,
  "from_status" text,
  "to_status" text,
  "note" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_alert_events_alert_id_fkey"
    FOREIGN KEY ("alert_id") REFERENCES "public"."mobilisation_alerts"("alert_id") ON DELETE CASCADE
);

COMMENT ON TABLE "public"."mobilisation_alert_events" IS
  'Audit trail for acknowledge, snooze and dismiss. Written by trigger so the client cannot skip it.';

CREATE TABLE IF NOT EXISTS "public"."mobilisation_notifications" (
  "notification_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "alert_id" bigint NOT NULL,
  "destination" text NOT NULL,
  "channel" text NOT NULL,
  "kind" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "error" text,
  "sent_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_notifications_unique" UNIQUE ("alert_id", "destination", "channel", "kind"),
  CONSTRAINT "mobilisation_notifications_channel_check" CHECK (
    "channel" IN ('email', 'push', 'slack', 'teams')
  ),
  CONSTRAINT "mobilisation_notifications_status_check" CHECK (
    "status" IN ('pending', 'sent', 'failed', 'skipped')
  ),
  CONSTRAINT "mobilisation_notifications_alert_id_fkey"
    FOREIGN KEY ("alert_id") REFERENCES "public"."mobilisation_alerts"("alert_id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_prefs" (
  "user_id" uuid PRIMARY KEY,
  "email_immediate" boolean NOT NULL DEFAULT true,
  "push_immediate" boolean NOT NULL DEFAULT false,
  "digest" text NOT NULL DEFAULT 'daily',
  "min_priority" text NOT NULL DEFAULT 'high',
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_prefs_digest_check" CHECK ("digest" IN ('off', 'daily', 'weekly')),
  CONSTRAINT "mobilisation_prefs_priority_check" CHECK ("min_priority" IN ('low', 'normal', 'high', 'critical')),
  CONSTRAINT "mobilisation_prefs_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_push_subscriptions" (
  "subscription_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" uuid NOT NULL,
  "endpoint" text NOT NULL,
  "p256dh" text NOT NULL,
  "auth" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_push_subscriptions_endpoint_unique" UNIQUE ("endpoint"),
  CONSTRAINT "mobilisation_push_subscriptions_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "public"."mobilisation_positions" (
  "position_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vessel_id" integer NOT NULL,
  "observed_at" timestamp with time zone NOT NULL,
  "latitude" numeric(9,6) NOT NULL,
  "longitude" numeric(9,6) NOT NULL,
  "sog_kn" numeric(6,2),
  "cog_deg" numeric(6,2),
  "destination" text,
  "eta" timestamp with time zone,
  "source" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_positions_unique" UNIQUE ("vessel_id", "observed_at", "source"),
  CONSTRAINT "mobilisation_positions_vessel_id_fkey"
    FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("vessel_id") ON DELETE CASCADE
);

COMMENT ON TABLE "public"."mobilisation_positions" IS
  'Recent AIS fixes for internal alerting only. Do not expose this table publicly or republish coordinates. The poller deletes rows older than 14 days.';

CREATE TABLE IF NOT EXISTS "public"."mobilisation_settings" (
  "id" integer PRIMARY KEY DEFAULT 1,
  "slack_webhook_url" text,
  "teams_webhook_url" text,
  "ais_provider" text NOT NULL DEFAULT 'datalastic',
  "ais_satellite_enabled" boolean NOT NULL DEFAULT false,
  "escalation_window_days" integer NOT NULL DEFAULT 42,
  "contact_email" text,
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "mobilisation_settings_singleton" CHECK ("id" = 1),
  CONSTRAINT "mobilisation_settings_window_check" CHECK ("escalation_window_days" BETWEEN 7 AND 180)
);

INSERT INTO "public"."mobilisation_settings" ("id") VALUES (1) ON CONFLICT DO NOTHING;

-- Audit status changes, including snooze expiry performed by the service role.
CREATE OR REPLACE FUNCTION "public"."mobilisation_alert_audit"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status OR NEW.snoozed_until IS DISTINCT FROM OLD.snoozed_until THEN
    INSERT INTO "public"."mobilisation_alert_events" (
      "alert_id", "actor_id", "action", "from_status", "to_status", "note"
    ) VALUES (
      NEW.alert_id,
      auth.uid(),
      CASE
        WHEN NEW.status = 'acknowledged' THEN 'acknowledged'
        WHEN NEW.status = 'snoozed' THEN 'snoozed'
        WHEN NEW.status = 'dismissed' THEN 'dismissed'
        WHEN OLD.status = 'snoozed' AND NEW.status = 'new' THEN 'unsnoozed'
        ELSE NEW.status
      END,
      OLD.status,
      NEW.status,
      NEW.status_note
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "trg_mobilisation_alert_audit" ON "public"."mobilisation_alerts";
CREATE TRIGGER "trg_mobilisation_alert_audit"
  AFTER UPDATE ON "public"."mobilisation_alerts"
  FOR EACH ROW EXECUTE FUNCTION "public"."mobilisation_alert_audit"();

DROP TRIGGER IF EXISTS "trg_vessels_updated_at" ON "public"."vessels";
CREATE TRIGGER "trg_vessels_updated_at" BEFORE UPDATE ON "public"."vessels"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();
DROP TRIGGER IF EXISTS "trg_geofences_updated_at" ON "public"."geofences";
CREATE TRIGGER "trg_geofences_updated_at" BEFORE UPDATE ON "public"."geofences"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();
DROP TRIGGER IF EXISTS "trg_mob_watch_contractors_updated_at" ON "public"."mobilisation_watch_contractors";
CREATE TRIGGER "trg_mob_watch_contractors_updated_at" BEFORE UPDATE ON "public"."mobilisation_watch_contractors"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();
DROP TRIGGER IF EXISTS "trg_mob_rules_updated_at" ON "public"."mobilisation_rules";
CREATE TRIGGER "trg_mob_rules_updated_at" BEFORE UPDATE ON "public"."mobilisation_rules"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();
DROP TRIGGER IF EXISTS "trg_mob_alerts_updated_at" ON "public"."mobilisation_alerts";
CREATE TRIGGER "trg_mob_alerts_updated_at" BEFORE UPDATE ON "public"."mobilisation_alerts"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();
DROP TRIGGER IF EXISTS "trg_mob_prefs_updated_at" ON "public"."mobilisation_prefs";
CREATE TRIGGER "trg_mob_prefs_updated_at" BEFORE UPDATE ON "public"."mobilisation_prefs"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();
DROP TRIGGER IF EXISTS "trg_mob_settings_updated_at" ON "public"."mobilisation_settings";
CREATE TRIGGER "trg_mob_settings_updated_at" BEFORE UPDATE ON "public"."mobilisation_settings"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();

-- Seed geofences. Same rings as src/lib/mobilisation/geofences.ts.
INSERT INTO "public"."geofences" ("name", "slug", "description", "geometry")
VALUES
  (
    'Carnarvon Basin / North West Shelf',
    'carnarvon-nws',
    'Commonwealth waters off the North West Cape through the North West Shelf. Editable.',
    '{"type":"Polygon","coordinates":[[[112.2,-22.6],[112.2,-19.0],[114.5,-18.2],[116.8,-18.6],[117.2,-20.2],[115.8,-21.8],[114.0,-22.7],[112.2,-22.6]]]}'::jsonb
  ),
  (
    'Browse Basin',
    'browse',
    'Browse Basin offshore northern Western Australia. Editable.',
    '{"type":"Polygon","coordinates":[[[120.5,-15.8],[120.5,-12.8],[124.8,-12.8],[124.8,-15.2],[122.5,-16.2],[120.5,-15.8]]]}'::jsonb
  ),
  (
    'Bonaparte Basin / Timor Sea',
    'bonaparte-timor',
    'Bonaparte Basin and the Australian Timor Sea. Bass Strait is not included.',
    '{"type":"Polygon","coordinates":[[[126.0,-14.2],[125.2,-11.2],[128.5,-9.8],[131.8,-10.2],[132.2,-13.6],[129.0,-14.6],[126.0,-14.2]]]}'::jsonb
  )
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "public"."mobilisation_watch_contractors" ("canonical_name", "aliases", "tier", "is_active")
VALUES
  ('Saipem', '{}', 'core', true),
  ('Allseas', '{}', 'core', true),
  ('Subsea7', '{Subsea 7}', 'core', true),
  ('McDermott', '{}', 'core', true),
  ('Fugro', '{}', 'core', true),
  ('DeepOcean', '{Shelf Subsea}', 'core', true),
  ('Van Oord', '{}', 'core', true),
  ('Vantris', '{Sapura}', 'core', true),
  ('DOF', '{}', 'adjacent', false),
  ('TechnipFMC', '{Technip}', 'adjacent', false),
  ('Heerema', '{}', 'adjacent', false),
  ('Boskalis', '{}', 'adjacent', false),
  ('DEME', '{}', 'adjacent', false),
  ('Petrofac', '{}', 'adjacent', false)
ON CONFLICT ("canonical_name") DO NOTHING;

INSERT INTO "public"."vessels" ("name", "vessel_type", "owner_name", "imo", "relevance", "notes")
VALUES
  ('Castorone', 'pipelay', 'Saipem', NULL, 'nw', NULL),
  ('Saipem Endeavour', 'pipelay', 'Saipem', NULL, 'nw', NULL),
  ('Saipem Constellation', 'construction', 'Saipem', NULL, 'nw', NULL),
  ('Audacia', 'pipelay', 'Allseas', NULL, 'nw', NULL),
  ('Sandpiper', 'pipelay', 'Allseas', NULL, 'nw', NULL),
  ('Fortitude', 'pipelay', 'Allseas', NULL, 'nw', NULL),
  ('Solitaire', 'pipelay', 'Allseas', NULL, 'global', 'Usually elsewhere / Bass Strait. Kept for global awareness, not NW alerts by default.'),
  ('Lorelay', 'pipelay', 'Allseas', NULL, 'global', 'Usually elsewhere / Bass Strait. Kept for global awareness.'),
  ('Pioneering Spirit', 'heavy_lift', 'Allseas', NULL, 'global', 'Usually elsewhere / Bass Strait. Kept for global awareness.'),
  ('Seven Oceans', 'pipelay', 'Subsea7', NULL, 'nw', NULL),
  ('Seven Oceanic', 'pipelay', 'Subsea7', NULL, 'nw', NULL),
  ('DLV 2000', 'pipelay', 'McDermott', NULL, 'nw', NULL),
  ('Fugro Etive', 'survey', 'Fugro', '9379686', 'nw', 'IMO confirmed.'),
  ('Fugro Equator', 'survey', 'Fugro', NULL, 'nw', NULL),
  ('Blue Essence', 'usv', 'Fugro', NULL, 'nw', 'Blue Essence USV fleet. Not a single hull; add individual IMOs when known.'),
  ('Southern Star', 'dsv', 'DeepOcean', NULL, 'nw', 'Shelf Subsea / DeepOcean APAC.'),
  ('Southern Nova', 'dsv', 'DeepOcean', NULL, 'nw', NULL),
  ('Oriental Dragon', 'dsv', 'DeepOcean', NULL, 'nw', NULL),
  ('Bravenes', 'rock_install', 'Van Oord', NULL, 'nw', 'Subsea rock-installation.'),
  ('Stornes', 'rock_install', 'Van Oord', NULL, 'nw', 'Subsea rock-installation.'),
  ('Nordnes', 'rock_install', 'Van Oord', NULL, 'nw', 'Subsea rock-installation.'),
  ('Van Oord dredger spread', 'dredger', 'Van Oord', NULL, 'nw', 'Placeholder for the dredger spread. Replace with named hulls.'),
  ('Sapura Constructor', 'construction', 'Vantris', NULL, 'nw', 'Vantris, formerly Sapura.'),
  ('Sapura 3500', 'pipelay', 'Vantris', NULL, 'low', 'Sapura PLSV. The six Sapura PLSVs are Brazil-committed; low NW relevance.'),
  ('Sapura 1200', 'pipelay', 'Vantris', NULL, 'low', 'Sapura PLSV. The six Sapura PLSVs are Brazil-committed; low NW relevance.')
ON CONFLICT ("name", "owner_name") DO NOTHING;

INSERT INTO "public"."mobilisation_watch_vessels" ("vessel_id", "is_active")
SELECT "vessel_id", true FROM "public"."vessels"
ON CONFLICT ("vessel_id") DO NOTHING;

INSERT INTO "public"."mobilisation_watch_keywords" ("keyword", "kind", "asx_ticker")
VALUES
  ('Australia', 'region', NULL),
  ('North West Shelf', 'region', NULL),
  ('Carnarvon', 'region', NULL),
  ('Browse', 'region', NULL),
  ('Bonaparte', 'region', NULL),
  ('Timor Sea', 'region', NULL),
  ('Dampier', 'region', NULL),
  ('Woodside', 'operator', 'WDS'),
  ('Santos', 'operator', 'STO'),
  ('Chevron', 'operator', NULL),
  ('INPEX', 'operator', NULL),
  ('Shell', 'operator', NULL),
  ('Jadestone', 'operator', NULL),
  ('Scarborough', 'project', NULL),
  ('Pluto', 'project', NULL),
  ('Gorgon', 'project', NULL),
  ('Wheatstone', 'project', NULL),
  ('Ichthys', 'project', NULL),
  ('Prelude', 'project', NULL),
  ('Barossa', 'project', NULL),
  ('Crux', 'project', NULL)
ON CONFLICT ("keyword", "kind") DO NOTHING;

-- Link watch rows to employers only on an exact name match, so a prefix
-- collision cannot attach the wrong company.
UPDATE "public"."mobilisation_watch_contractors" AS w
SET "employer_id" = e."employer_id"
FROM "public"."employers" AS e
WHERE w."employer_id" IS NULL
  AND e."is_active" = true
  AND lower(e."employer_name") = lower(w."canonical_name");

UPDATE "public"."vessels" AS v
SET "owner_operator_id" = e."employer_id"
FROM "public"."employers" AS e
WHERE v."owner_operator_id" IS NULL
  AND e."is_active" = true
  AND (
    lower(e."employer_name") = lower(v."owner_name")
    OR lower(coalesce(e."trading_name", '')) = lower(v."owner_name")
  );

UPDATE "public"."mobilisation_watch_contractors" AS w
SET "employer_id" = v."owner_operator_id"
FROM "public"."vessels" AS v
WHERE w."employer_id" IS NULL
  AND v."owner_operator_id" IS NOT NULL
  AND lower(v."owner_name") = lower(w."canonical_name");

INSERT INTO "public"."mobilisation_sources"
  ("source_key", "layer", "display_name", "poll_interval_minutes", "enabled", "config")
VALUES
  (
    'nopsema_ep', 'regulatory', 'NOPSEMA environment plans', 1440, true,
    '{"listings":[{"key":"under_assessment","label":"NOPSEMA EP under assessment","url":"https://info.nopsema.gov.au/home/under_assessment_petroleum"},{"key":"approved","label":"NOPSEMA approved activities","url":"https://info.nopsema.gov.au/home/approved_projects_and_activities"}]}'::jsonb
  ),
  (
    'nopsema_notices', 'regulatory', 'NOPSEMA notices', 1440, true,
    '{"pages":["https://www.nopsema.gov.au/news/"]}'::jsonb
  ),
  (
    'nopta', 'regulatory', 'NOPTA titles', 1440, false,
    '{"pages":["https://www.nopta.gov.au/"]}'::jsonb
  ),
  (
    'asx', 'commercial', 'ASX announcements', 60, true,
    '{}'::jsonb
  ),
  (
    'trade_press', 'commercial', 'Offshore trade press', 360, true,
    '{"feeds":[{"name":"Offshore Energy","url":"https://www.offshore-energy.biz/feed/"},{"name":"gCaptain","url":"https://gcaptain.com/feed/"},{"name":"Splash247","url":"https://splash247.com/feed/"},{"name":"Baird Maritime","url":"https://www.bairdmaritime.com/feed/"}]}'::jsonb
  ),
  (
    'gdelt', 'commercial', 'GDELT', 360, true, '{}'::jsonb
  ),
  (
    'newsapi', 'commercial', 'NewsAPI', 360, true, '{}'::jsonb
  ),
  (
    'ais', 'ais', 'AIS positions', 30, true, '{}'::jsonb
  )
ON CONFLICT ("source_key") DO NOTHING;

INSERT INTO "public"."mobilisation_rules" ("code", "name", "description", "enabled", "priority", "config")
VALUES
  (
    'vessel_geofence',
    'Vessel entering or inbound',
    'A watchlisted vessel enters a NW geofence, or its course reaches one inside the horizon. Destination text alone stays under the confidence line.',
    true, 'high', '{"minConfidence":0.55}'::jsonb
  ),
  (
    'regulatory_watch',
    'NOPSEMA activity',
    'A new or varied environment plan or activity names a watchlisted contractor, operator, vessel or project in region.',
    true, 'normal', '{"minConfidence":0.5}'::jsonb
  ),
  (
    'commercial_watch',
    'Award or news',
    'ASX or trade press matches a watchlisted contractor plus Australia, a project, or an operator.',
    true, 'normal', '{"minConfidence":0.55}'::jsonb
  ),
  (
    'imminent_mobilisation',
    'Cross-layer mobilisation',
    'Two or more layers fire for the same contractor inside the escalation window.',
    true, 'critical', '{"windowDays":42,"minLayers":2,"minConfidence":0.6}'::jsonb
  )
ON CONFLICT ("code") DO NOTHING;

-- Grants and RLS. Staff (admin/user) maintain the watchlist. Every signed-in
-- user can read the feed. Viewers do not write. Service role bypasses RLS
-- for the pollers.

ALTER TABLE "public"."vessels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."geofences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_watch_contractors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_watch_vessels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_watch_keywords" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_signals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_alerts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_alert_signals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_alert_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_prefs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_push_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_positions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mobilisation_settings" ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'vessels', 'geofences', 'mobilisation_watch_contractors', 'mobilisation_watch_vessels',
    'mobilisation_watch_keywords', 'mobilisation_sources', 'mobilisation_rules',
    'mobilisation_signals', 'mobilisation_alerts', 'mobilisation_alert_signals',
    'mobilisation_alert_events', 'mobilisation_notifications', 'mobilisation_prefs',
    'mobilisation_push_subscriptions', 'mobilisation_positions', 'mobilisation_settings'
  ]
  LOOP
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon', t);
    EXECUTE format('GRANT SELECT ON TABLE public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON TABLE public.%I TO service_role', t);
  END LOOP;
END $$;

GRANT INSERT, UPDATE, DELETE ON TABLE "public"."vessels" TO "authenticated";
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."geofences" TO "authenticated";
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."mobilisation_watch_contractors" TO "authenticated";
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."mobilisation_watch_vessels" TO "authenticated";
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."mobilisation_watch_keywords" TO "authenticated";
GRANT UPDATE ON TABLE "public"."mobilisation_rules" TO "authenticated";
GRANT UPDATE ON TABLE "public"."mobilisation_alerts" TO "authenticated";
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."mobilisation_prefs" TO "authenticated";
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."mobilisation_push_subscriptions" TO "authenticated";
GRANT UPDATE ON TABLE "public"."mobilisation_settings" TO "authenticated";
GRANT UPDATE ON TABLE "public"."mobilisation_sources" TO "authenticated";

CREATE POLICY "mobilisation read vessels" ON "public"."vessels"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation write vessels" ON "public"."vessels"
  FOR ALL TO "authenticated"
  USING ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']))
  WITH CHECK ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']));

CREATE POLICY "mobilisation read geofences" ON "public"."geofences"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation write geofences" ON "public"."geofences"
  FOR ALL TO "authenticated"
  USING ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']))
  WITH CHECK ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']));

CREATE POLICY "mobilisation read watch contractors" ON "public"."mobilisation_watch_contractors"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation write watch contractors" ON "public"."mobilisation_watch_contractors"
  FOR ALL TO "authenticated"
  USING ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']))
  WITH CHECK ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']));

CREATE POLICY "mobilisation read watch vessels" ON "public"."mobilisation_watch_vessels"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation write watch vessels" ON "public"."mobilisation_watch_vessels"
  FOR ALL TO "authenticated"
  USING ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']))
  WITH CHECK ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']));

CREATE POLICY "mobilisation read keywords" ON "public"."mobilisation_watch_keywords"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation write keywords" ON "public"."mobilisation_watch_keywords"
  FOR ALL TO "authenticated"
  USING ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']))
  WITH CHECK ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']));

CREATE POLICY "mobilisation read sources" ON "public"."mobilisation_sources"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation admin update sources" ON "public"."mobilisation_sources"
  FOR UPDATE TO "authenticated"
  USING ("public"."get_user_role"() = 'admin')
  WITH CHECK ("public"."get_user_role"() = 'admin');

CREATE POLICY "mobilisation read rules" ON "public"."mobilisation_rules"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation admin update rules" ON "public"."mobilisation_rules"
  FOR UPDATE TO "authenticated"
  USING ("public"."get_user_role"() = 'admin')
  WITH CHECK ("public"."get_user_role"() = 'admin');

CREATE POLICY "mobilisation read signals" ON "public"."mobilisation_signals"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation read alerts" ON "public"."mobilisation_alerts"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation update alerts" ON "public"."mobilisation_alerts"
  FOR UPDATE TO "authenticated"
  USING ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']))
  WITH CHECK ("public"."get_user_role"() = ANY (ARRAY['admin', 'user']));

CREATE POLICY "mobilisation read alert signals" ON "public"."mobilisation_alert_signals"
  FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mobilisation read alert events" ON "public"."mobilisation_alert_events"
  FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "mobilisation read own notifications" ON "public"."mobilisation_notifications"
  FOR SELECT TO "authenticated"
  USING ("destination" = 'user:' || auth.uid()::text OR "public"."get_user_role"() = 'admin');

CREATE POLICY "mobilisation read own prefs" ON "public"."mobilisation_prefs"
  FOR SELECT TO "authenticated"
  USING ("user_id" = auth.uid() OR "public"."get_user_role"() = 'admin');
CREATE POLICY "mobilisation write own prefs" ON "public"."mobilisation_prefs"
  FOR ALL TO "authenticated"
  USING ("user_id" = auth.uid())
  WITH CHECK ("user_id" = auth.uid());

CREATE POLICY "mobilisation read own push" ON "public"."mobilisation_push_subscriptions"
  FOR SELECT TO "authenticated" USING ("user_id" = auth.uid());
CREATE POLICY "mobilisation write own push" ON "public"."mobilisation_push_subscriptions"
  FOR ALL TO "authenticated"
  USING ("user_id" = auth.uid())
  WITH CHECK ("user_id" = auth.uid());

CREATE POLICY "mobilisation read positions" ON "public"."mobilisation_positions"
  FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "mobilisation admin settings" ON "public"."mobilisation_settings"
  FOR SELECT TO "authenticated" USING ("public"."get_user_role"() = 'admin');
CREATE POLICY "mobilisation admin update settings" ON "public"."mobilisation_settings"
  FOR UPDATE TO "authenticated"
  USING ("public"."get_user_role"() = 'admin')
  WITH CHECK ("public"."get_user_role"() = 'admin');

DO $$
DECLARE
  seq text;
  spec text;
  tbl text;
  col text;
BEGIN
  FOREACH spec IN ARRAY ARRAY[
    'vessels.vessel_id',
    'geofences.geofence_id',
    'mobilisation_watch_contractors.watch_id',
    'mobilisation_watch_vessels.watch_vessel_id',
    'mobilisation_watch_keywords.keyword_id',
    'mobilisation_rules.rule_id',
    'mobilisation_signals.signal_id',
    'mobilisation_alerts.alert_id',
    'mobilisation_alert_events.event_id',
    'mobilisation_notifications.notification_id',
    'mobilisation_push_subscriptions.subscription_id',
    'mobilisation_positions.position_id'
  ]
  LOOP
    tbl := split_part(spec, '.', 1);
    col := split_part(spec, '.', 2);
    seq := pg_get_serial_sequence('public.' || tbl, col);
    IF seq IS NOT NULL THEN
      EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated, service_role', seq);
    END IF;
  END LOOP;
END $$;
