-- DA0.3 PRODUCTION RUN SHEET — step P2 (mutating: the schema migration + its ledger row, one transaction)
-- Project: production (gteygwfgjvczanmrwgbr). Supabase dashboard → SQL Editor → New query → paste this
-- whole file → Run. One submission = this whole file. Prepared by the agent from the committed scripts
-- in the parent folder; the agent never runs anything on production.
-- What it does: applies supabase/migrations/20260922120000_da0_3_name_match_reviews.sql verbatim inside one transaction (widens both alias-source CHECKs; creates name_match_reviews with RLS and grants, fold_name(), decide_name_match(), two triggers, indexes; adds workers.employer_name_raw, worksite_name_raw, names_import_id), then records the ledger row. Writes no application row.
-- Expect: the one result row at the end: version 20260922120000, name da0_3_name_match_reviews, nmr_present t, fold_name_present t, decide_present t, raw_columns 3.
-- Paste back: the one result row (or the error).
-- If anything raises, the transaction (where there is one) has rolled back and nothing changed: paste the error and stop.

BEGIN;
SET LOCAL oux.env = 'production';

-- DA0.3 — Stop the bleed (docs/data-architecture/wp/da0.3.md §2.3).
--
-- (a) Widen the alias-source CHECKs so the reference wizard's employer
--     aliases save and so imports, the OA-universe loads and the FWC loads
--     write one vocabulary: merge | manual | import | oa_universe | fwc.
-- (b) `name_match_reviews`: the review queue for employer and worksite
--     strings an import could not resolve, generalised from
--     `upcoming_project_employers` (same status / method vocabulary).
--     Writes go through `decide_name_match()` (admin, SECURITY DEFINER) and
--     the service role only; authenticated users may read.
-- (c) `workers.employer_name_raw`, `worksite_name_raw`, `names_import_id`:
--     the string as last received from an import and the import that
--     supplied it — the back-fill key when a queued name is decided.
--
-- Depends only on baseline objects (20260908050000): import_logs, employers,
-- worksites, workers, employer_name_aliases, worksite_name_aliases,
-- update_updated_at(), is_admin(), auth.users. No application row is changed.
-- Idempotent: every statement is IF NOT EXISTS / OR REPLACE / DROP IF EXISTS.

-- ── (a) Alias source vocabulary ─────────────────────────────────────────────

ALTER TABLE "public"."employer_name_aliases"
  DROP CONSTRAINT IF EXISTS "employer_name_aliases_source_check";
ALTER TABLE "public"."employer_name_aliases"
  ADD CONSTRAINT "employer_name_aliases_source_check"
  CHECK (("source")::text = ANY (ARRAY['merge', 'manual', 'import', 'oa_universe', 'fwc']));

-- Same five values on worksite_name_aliases (was import | manual | merge):
-- the resolver and the decision function write both tables with one
-- vocabulary (plan §7, input 6).
ALTER TABLE "public"."worksite_name_aliases"
  DROP CONSTRAINT IF EXISTS "worksite_name_aliases_source_check";
ALTER TABLE "public"."worksite_name_aliases"
  ADD CONSTRAINT "worksite_name_aliases_source_check"
  CHECK (("source")::text = ANY (ARRAY['merge', 'manual', 'import', 'oa_universe', 'fwc']));

-- ── Name folding, shared by SQL and TypeScript ──────────────────────────────

-- Byte-for-byte the rule of apps/organising-db/src/lib/import/name-fold.ts:
-- every run of whitespace becomes one space, outer space is trimmed, then
-- lower-cased. Legal suffixes are NOT stripped (exact means exact after
-- folding; suffix tolerance is the fuzzy step's job).
CREATE OR REPLACE FUNCTION "public"."fold_name"("p" "text") RETURNS "text"
    LANGUAGE "sql" IMMUTABLE STRICT PARALLEL SAFE
    AS $$
  SELECT lower(btrim(regexp_replace(p, '\s+', ' ', 'g')));
$$;

ALTER FUNCTION "public"."fold_name"("p" "text") OWNER TO "postgres";

COMMENT ON FUNCTION "public"."fold_name"("p" "text") IS
  'Exact-match key for employer / worksite strings: whitespace collapsed to one space, trimmed, lower-cased. Mirrors lib/import/name-fold.ts.';

-- ── (b) name_match_reviews ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "public"."name_match_reviews" (
  "id"                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entity"               text NOT NULL,
  "raw_name"             text NOT NULL,
  "normalised_name"      text NOT NULL,
  "import_id"            integer REFERENCES "public"."import_logs"("import_id") ON DELETE SET NULL,
  "status"               text NOT NULL DEFAULT 'needs_review',
  "match_score"          numeric(4,3),
  "match_method"         text,
  "candidate_proposals"  jsonb NOT NULL DEFAULT '[]'::jsonb,
  "resolved_employer_id" integer REFERENCES "public"."employers"("employer_id") ON DELETE SET NULL,
  "resolved_worksite_id" integer REFERENCES "public"."worksites"("worksite_id") ON DELETE SET NULL,
  "occurrences"          integer NOT NULL DEFAULT 1,
  "source_context"       jsonb NOT NULL DEFAULT '{}'::jsonb,
  "notes"                text,
  "decided_by"           uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
  "decided_at"           timestamp with time zone,
  "created_by"           uuid REFERENCES "auth"."users"("id") ON DELETE SET NULL,
  "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"           timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "name_match_reviews_entity_check"
    CHECK ("entity" IN ('employer', 'worksite')),
  CONSTRAINT "name_match_reviews_raw_name_check"
    CHECK (char_length(btrim("raw_name")) BETWEEN 1 AND 200),
  CONSTRAINT "name_match_reviews_status_check"
    CHECK ("status" IN ('auto', 'needs_review', 'confirmed', 'overridden', 'rejected', 'unmatched')),
  CONSTRAINT "name_match_reviews_match_method_check"
    CHECK ("match_method" IS NULL OR "match_method" IN ('exact', 'alias', 'fuzzy', 'manual', 'created')),
  CONSTRAINT "name_match_reviews_resolved_entity_check"
    CHECK (("entity" = 'employer' AND "resolved_worksite_id" IS NULL)
        OR ("entity" = 'worksite' AND "resolved_employer_id" IS NULL)),
  CONSTRAINT "name_match_reviews_decided_check"
    CHECK (("status" IN ('confirmed', 'overridden', 'rejected')) = ("decided_at" IS NOT NULL))
);

ALTER TABLE "public"."name_match_reviews" OWNER TO "postgres";

COMMENT ON TABLE "public"."name_match_reviews" IS
  'Review queue for employer / worksite strings an import could not resolve (DA0.3). One row per distinct folded string per import. status: auto (fuzzy >= 0.92 accepted, alias written, kept for audit) | needs_review (proposals, none dominant; open) | unmatched (no proposal; open) | confirmed (reviewer accepted a proposal or created a row) | overridden (reviewer mapped it by search) | rejected (not an employer / worksite; sticky — the resolver will not re-queue the string). Exact and alias hits are not recorded. Writes only through decide_name_match() (admins) and the service role.';
COMMENT ON COLUMN "public"."name_match_reviews"."candidate_proposals" IS
  'Top-3 proposals [{id, name, score, is_principal}] from @oa/employer-matching.';
COMMENT ON COLUMN "public"."name_match_reviews"."source_context" IS
  '{other_raw_name, import_type, weekly_batch_id, source_kinds[]}: what accompanied the string in the file. No FK on weekly_batch_id.';

CREATE INDEX IF NOT EXISTS "idx_name_match_reviews_open"
  ON "public"."name_match_reviews" ("entity", "created_at" DESC)
  WHERE "status" IN ('needs_review', 'unmatched');
CREATE INDEX IF NOT EXISTS "idx_name_match_reviews_entity_norm"
  ON "public"."name_match_reviews" ("entity", "normalised_name");
CREATE INDEX IF NOT EXISTS "idx_name_match_reviews_import"
  ON "public"."name_match_reviews" ("import_id") WHERE "import_id" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_name_match_reviews_employer"
  ON "public"."name_match_reviews" ("resolved_employer_id") WHERE "resolved_employer_id" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_name_match_reviews_worksite"
  ON "public"."name_match_reviews" ("resolved_worksite_id") WHERE "resolved_worksite_id" IS NOT NULL;
-- one row per string per import (the resolver upserts on this). Not a
-- partial index: PostgREST's on_conflict cannot name an index predicate, and
-- NULL import_ids never collide (NULLS DISTINCT), so the semantics are the
-- same as "WHERE import_id IS NOT NULL".
CREATE UNIQUE INDEX IF NOT EXISTS "uq_name_match_reviews_import_entity_norm"
  ON "public"."name_match_reviews" ("import_id", "entity", "normalised_name");

CREATE OR REPLACE FUNCTION "public"."name_match_reviews_fold"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.normalised_name := public.fold_name(NEW.raw_name);
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."name_match_reviews_fold"() OWNER TO "postgres";

CREATE OR REPLACE TRIGGER "trg_name_match_reviews_fold"
  BEFORE INSERT OR UPDATE OF "raw_name" ON "public"."name_match_reviews"
  FOR EACH ROW EXECUTE FUNCTION "public"."name_match_reviews_fold"();
CREATE OR REPLACE TRIGGER "trg_name_match_reviews_updated_at"
  BEFORE UPDATE ON "public"."name_match_reviews"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at"();

ALTER TABLE "public"."name_match_reviews" ENABLE ROW LEVEL SECURITY;

-- Mirrors upcoming_project_employers, which has exactly one policy
-- (baseline:28990-28993: SELECT TO authenticated USING (true)); writes there
-- come from the scraper (service role) and the SECURITY DEFINER
-- confirm_upcoming_project_match() gated by is_admin(). Same here.
DROP POLICY IF EXISTS "name_match_reviews_select_authed" ON "public"."name_match_reviews";
CREATE POLICY "name_match_reviews_select_authed"
  ON "public"."name_match_reviews" FOR SELECT TO "authenticated" USING (true);

-- Grants: the baseline's default privileges grant ALL (including TRUNCATE,
-- which RLS does not cover) to anon AND authenticated on every new public
-- table. Revoke both, then grant authenticated SELECT only; the RLS policy
-- above then decides which rows it may read.
REVOKE ALL ON TABLE "public"."name_match_reviews" FROM PUBLIC, "anon", "authenticated";
GRANT SELECT ON TABLE "public"."name_match_reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."name_match_reviews" TO "service_role";

DO $$
DECLARE
  seq text;
BEGIN
  seq := pg_get_serial_sequence('public.name_match_reviews', 'id');
  IF seq IS NOT NULL THEN
    EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM PUBLIC, anon, authenticated', seq);
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO service_role', seq);
  END IF;
END $$;

-- ── (c) Raw names on the worker row ─────────────────────────────────────────

ALTER TABLE "public"."workers"
  ADD COLUMN IF NOT EXISTS "employer_name_raw" text,
  ADD COLUMN IF NOT EXISTS "worksite_name_raw" text,
  ADD COLUMN IF NOT EXISTS "names_import_id" integer
    REFERENCES "public"."import_logs"("import_id") ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "idx_workers_names_import"
  ON "public"."workers" ("names_import_id") WHERE "names_import_id" IS NOT NULL;
COMMENT ON COLUMN "public"."workers"."employer_name_raw" IS
  'Employer string as last received from an import (organisation name, not personal data); the back-fill key when a queued name is decided.';
COMMENT ON COLUMN "public"."workers"."worksite_name_raw" IS
  'Worksite string as last received from an import; the back-fill key when a queued name is decided.';
COMMENT ON COLUMN "public"."workers"."names_import_id" IS
  'The import_logs row that last supplied employer_name_raw / worksite_name_raw.';

-- ── The decision function (alias + queue row + back-fill in one statement) ──

-- Mirrors confirm_upcoming_project_match(payload jsonb) (baseline:1512-1620).
-- Returns jsonb because the caller needs the back-filled worker ids for the
-- campaign-universe sync.
--
--   payload: { id, action: 'confirm' | 'override' | 'create' | 'reject' | 'reopen',
--              employer_id? | worksite_id?     (confirm / override: the target row;
--                                               confirm falls back to resolved_*),
--              create?: { employer_name, trading_name?, employer_category? }
--                     | { worksite_name, worksite_type, is_offshore? },
--              notes? }
--   returns: { review: <row>, alias_written: bool, backfilled_worker_ids: int[],
--              siblings_resolved: int }
CREATE OR REPLACE FUNCTION "public"."decide_name_match"("payload" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_id            bigint;
  v_action        text;
  v_notes         text;
  v_create        jsonb;
  v_target        integer;
  v_target_name   text;
  v_target_alt    text;
  v_other_name    text;
  v_status        text;
  v_method        text;
  v_n             integer := 0;
  v_row           public.name_match_reviews;
  v_alias_written boolean := false;
  v_backfilled    integer[] := '{}'::integer[];
  v_siblings      integer := 0;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Only admins may decide name matches';
  END IF;

  v_id     := NULLIF(payload->>'id', '')::bigint;
  v_action := payload->>'action';
  v_notes  := payload->>'notes';
  v_create := CASE WHEN jsonb_typeof(payload->'create') = 'object' THEN payload->'create' ELSE NULL END;

  IF v_id IS NULL OR v_action IS NULL THEN
    RAISE EXCEPTION 'payload must include id and action';
  END IF;
  IF v_action NOT IN ('confirm', 'override', 'create', 'reject', 'reopen') THEN
    RAISE EXCEPTION 'unsupported action: %', v_action;
  END IF;

  SELECT * INTO v_row FROM public.name_match_reviews WHERE id = v_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'name_match_reviews row % not found', v_id;
  END IF;

  IF v_action IN ('confirm', 'override', 'create') THEN
    -- 1. Only an open (or auto) row can be decided; reopen a decided one first.
    IF v_row.status NOT IN ('needs_review', 'unmatched', 'auto') THEN
      RAISE EXCEPTION 'review % is already %; reopen it first', v_id, v_row.status;
    END IF;

    -- 2. The target row: created here (the only insert into employers /
    --    worksites on the import path) or named by the reviewer.
    IF v_action = 'create' THEN
      IF v_create IS NULL THEN
        RAISE EXCEPTION 'create requires a create object';
      END IF;
      BEGIN
        IF v_row.entity = 'employer' THEN
          IF NULLIF(btrim(v_create->>'employer_name'), '') IS NULL THEN
            RAISE EXCEPTION 'create requires employer_name';
          END IF;
          INSERT INTO public.employers (employer_name, trading_name, employer_category, is_active)
          VALUES (
            btrim(v_create->>'employer_name'),
            NULLIF(btrim(v_create->>'trading_name'), ''),
            NULLIF(btrim(v_create->>'employer_category'), ''),
            true
          )
          RETURNING employer_id INTO v_target;
        ELSE
          IF NULLIF(btrim(v_create->>'worksite_name'), '') IS NULL
             OR NULLIF(btrim(v_create->>'worksite_type'), '') IS NULL THEN
            RAISE EXCEPTION 'create requires worksite_name and worksite_type';
          END IF;
          INSERT INTO public.worksites (worksite_name, worksite_type, is_offshore, is_active)
          VALUES (
            btrim(v_create->>'worksite_name'),
            btrim(v_create->>'worksite_type'),
            COALESCE(NULLIF(v_create->>'is_offshore', '')::boolean, false),
            true
          )
          RETURNING worksite_id INTO v_target;
        END IF;
      EXCEPTION WHEN unique_violation THEN
        RAISE EXCEPTION '% "%" already exists — search for it instead',
          v_row.entity, btrim(COALESCE(v_create->>'employer_name', v_create->>'worksite_name'));
      END;
    ELSE
      v_target := COALESCE(
        NULLIF(CASE WHEN v_row.entity = 'employer' THEN payload->>'employer_id' ELSE payload->>'worksite_id' END, '')::integer,
        CASE WHEN v_row.entity = 'employer' THEN v_row.resolved_employer_id ELSE v_row.resolved_worksite_id END
      );
      IF v_target IS NULL THEN
        RAISE EXCEPTION '% requires %_id', v_action, v_row.entity;
      END IF;
      -- confirm accepts one of the resolver's proposals (provenance stays
      -- 'fuzzy' with its score); a row found by search is an override.
      IF v_action = 'confirm' AND NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(v_row.candidate_proposals) p
         WHERE (p->>'id')::integer = v_target)
      THEN
        RAISE EXCEPTION 'target % % is not one of the proposals; use override', v_row.entity, v_target;
      END IF;
    END IF;

    IF v_row.entity = 'employer' THEN
      SELECT e.employer_name, e.trading_name INTO v_target_name, v_target_alt
        FROM public.employers e WHERE e.employer_id = v_target;
    ELSE
      SELECT w.worksite_name, NULL INTO v_target_name, v_target_alt
        FROM public.worksites w WHERE w.worksite_id = v_target;
    END IF;
    IF v_target_name IS NULL THEN
      RAISE EXCEPTION '% % not found', v_row.entity, v_target;
    END IF;

    -- 3. Ambiguity guard (the DA1.4 alias lock, applied per decision until
    --    the unique index lands): the same folded string must not already be
    --    an alias of a different row of the same entity.
    IF v_row.entity = 'employer' THEN
      SELECT e.employer_name INTO v_other_name
        FROM public.employer_name_aliases a
        JOIN public.employers e ON e.employer_id = a.employer_id
       WHERE public.fold_name(a.alias_name::text) = v_row.normalised_name
         AND a.employer_id <> v_target
       LIMIT 1;
    ELSE
      SELECT w.worksite_name INTO v_other_name
        FROM public.worksite_name_aliases a
        JOIN public.worksites w ON w.worksite_id = a.worksite_id
       WHERE public.fold_name(a.alias_name::text) = v_row.normalised_name
         AND a.worksite_id <> v_target
       LIMIT 1;
    END IF;
    IF v_other_name IS NOT NULL THEN
      RAISE EXCEPTION 'alias "%" already points at %; resolve that alias first',
        btrim(v_row.raw_name), v_other_name;
    END IF;

    -- 4. Alias write when the raw string is not the canonical (or trading)
    --    name itself. source = 'import' for every accepted match; the
    --    per-row unique index (lower(btrim(alias_name))) is honoured.
    IF v_row.normalised_name <> public.fold_name(v_target_name)
       AND (v_target_alt IS NULL OR v_row.normalised_name <> public.fold_name(v_target_alt)) THEN
      IF v_row.entity = 'employer' THEN
        INSERT INTO public.employer_name_aliases (employer_id, alias_name, source, created_by)
        SELECT v_target, btrim(v_row.raw_name), 'import', auth.uid()
         WHERE NOT EXISTS (
           SELECT 1 FROM public.employer_name_aliases x
            WHERE x.employer_id = v_target
              AND lower(btrim(x.alias_name)) = lower(btrim(v_row.raw_name)));
      ELSE
        INSERT INTO public.worksite_name_aliases (worksite_id, alias_name, source, created_by)
        SELECT v_target, btrim(v_row.raw_name), 'import', auth.uid()
         WHERE NOT EXISTS (
           SELECT 1 FROM public.worksite_name_aliases x
            WHERE x.worksite_id = v_target
              AND lower(btrim(x.alias_name)) = lower(btrim(v_row.raw_name)));
      END IF;
      GET DIAGNOSTICS v_n = ROW_COUNT;
      v_alias_written := v_n > 0;
    END IF;

    v_status := CASE WHEN v_action = 'override' THEN 'overridden' ELSE 'confirmed' END;
    v_method := CASE v_action
                  WHEN 'override' THEN 'manual'
                  WHEN 'create'   THEN 'created'
                  ELSE COALESCE(v_row.match_method, 'fuzzy')
                END;

    -- 5. Back-fill: only a NULL FK is filled, only where the folded raw
    --    string matches, and only for workers whose names came from an
    --    import that queued this string. Nothing non-null is overwritten.
    -- 6. Sibling open rows for the same folded string (other imports) are
    --    resolved with the same target.
    -- 7. The decided row.
    IF v_row.entity = 'employer' THEN
      WITH upd AS (
        UPDATE public.workers w
           SET employer_id = v_target, updated_at = now()
         WHERE w.employer_id IS NULL
           AND w.employer_name_raw IS NOT NULL
           AND public.fold_name(w.employer_name_raw) = v_row.normalised_name
           AND w.names_import_id IN (
             SELECT r.import_id FROM public.name_match_reviews r
              WHERE r.entity = v_row.entity AND r.normalised_name = v_row.normalised_name
                AND r.import_id IS NOT NULL)
        RETURNING w.worker_id)
      SELECT COALESCE(array_agg(worker_id ORDER BY worker_id), '{}'::integer[]) INTO v_backfilled FROM upd;

      UPDATE public.name_match_reviews
         SET status = v_status, match_method = v_method,
             match_score = CASE WHEN v_action = 'confirm' THEN match_score ELSE NULL END,
             resolved_employer_id = v_target,
             decided_by = auth.uid(), decided_at = now(),
             notes = 'resolved with review ' || v_id
       WHERE entity = v_row.entity AND normalised_name = v_row.normalised_name
         AND id <> v_id AND status IN ('needs_review', 'unmatched');
      GET DIAGNOSTICS v_siblings = ROW_COUNT;

      UPDATE public.name_match_reviews
         SET status = v_status, match_method = v_method,
             match_score = CASE WHEN v_action = 'confirm' THEN match_score ELSE NULL END,
             resolved_employer_id = v_target,
             decided_by = auth.uid(), decided_at = now(), notes = v_notes
       WHERE id = v_id
       RETURNING * INTO v_row;
    ELSE
      WITH upd AS (
        UPDATE public.workers w
           SET worksite_id = v_target, updated_at = now()
         WHERE w.worksite_id IS NULL
           AND w.worksite_name_raw IS NOT NULL
           AND public.fold_name(w.worksite_name_raw) = v_row.normalised_name
           AND w.names_import_id IN (
             SELECT r.import_id FROM public.name_match_reviews r
              WHERE r.entity = v_row.entity AND r.normalised_name = v_row.normalised_name
                AND r.import_id IS NOT NULL)
        RETURNING w.worker_id)
      SELECT COALESCE(array_agg(worker_id ORDER BY worker_id), '{}'::integer[]) INTO v_backfilled FROM upd;

      UPDATE public.name_match_reviews
         SET status = v_status, match_method = v_method,
             match_score = CASE WHEN v_action = 'confirm' THEN match_score ELSE NULL END,
             resolved_worksite_id = v_target,
             decided_by = auth.uid(), decided_at = now(),
             notes = 'resolved with review ' || v_id
       WHERE entity = v_row.entity AND normalised_name = v_row.normalised_name
         AND id <> v_id AND status IN ('needs_review', 'unmatched');
      GET DIAGNOSTICS v_siblings = ROW_COUNT;

      UPDATE public.name_match_reviews
         SET status = v_status, match_method = v_method,
             match_score = CASE WHEN v_action = 'confirm' THEN match_score ELSE NULL END,
             resolved_worksite_id = v_target,
             decided_by = auth.uid(), decided_at = now(), notes = v_notes
       WHERE id = v_id
       RETURNING * INTO v_row;
    END IF;

  ELSIF v_action = 'reject' THEN
    IF v_row.status NOT IN ('needs_review', 'unmatched', 'auto') THEN
      RAISE EXCEPTION 'review % is already %; reopen it first', v_id, v_row.status;
    END IF;
    -- Sticky: the resolver returns `rejected` for this folded string on later
    -- imports and does not re-queue it. No alias, no back-fill.
    UPDATE public.name_match_reviews
       SET status = 'rejected', match_method = NULL, match_score = NULL,
           resolved_employer_id = NULL, resolved_worksite_id = NULL,
           decided_by = auth.uid(), decided_at = now(),
           notes = 'resolved with review ' || v_id
     WHERE entity = v_row.entity AND normalised_name = v_row.normalised_name
       AND id <> v_id AND status IN ('needs_review', 'unmatched');
    GET DIAGNOSTICS v_siblings = ROW_COUNT;

    UPDATE public.name_match_reviews
       SET status = 'rejected', match_method = NULL, match_score = NULL,
           resolved_employer_id = NULL, resolved_worksite_id = NULL,
           decided_by = auth.uid(), decided_at = now(), notes = v_notes
     WHERE id = v_id
     RETURNING * INTO v_row;

  ELSIF v_action = 'reopen' THEN
    IF v_row.status NOT IN ('confirmed', 'overridden', 'rejected') THEN
      RAISE EXCEPTION 'review % is %; only a decided review can be reopened', v_id, v_row.status;
    END IF;
    -- The alias and the back-fill are not reverted (plan §2.3.4; an admin
    -- removes a wrong alias with the existing delete policy).
    UPDATE public.name_match_reviews
       SET status = CASE WHEN candidate_proposals = '[]'::jsonb THEN 'unmatched' ELSE 'needs_review' END,
           match_method = CASE WHEN match_method IN ('manual', 'created') THEN NULL ELSE match_method END,
           resolved_employer_id = NULL, resolved_worksite_id = NULL,
           decided_by = NULL, decided_at = NULL,
           notes = COALESCE(v_notes, notes)
     WHERE id = v_id
     RETURNING * INTO v_row;
  END IF;

  RETURN jsonb_build_object(
    'review', to_jsonb(v_row),
    'alias_written', v_alias_written,
    'backfilled_worker_ids', to_jsonb(v_backfilled),
    'siblings_resolved', v_siblings
  );
END;
$$;

ALTER FUNCTION "public"."decide_name_match"("payload" "jsonb") OWNER TO "postgres";

COMMENT ON FUNCTION "public"."decide_name_match"("payload" "jsonb") IS
  'Admin decision on a name_match_reviews row: confirm / override / create / reject / reopen. Writes the alias, back-fills null worker FKs by the persisted raw name and import, resolves sibling rows, in one transaction.';

-- The baseline's default privileges grant functions to anon; this one is for
-- signed-in admins (is_admin() inside) and the service role.
REVOKE ALL ON FUNCTION "public"."decide_name_match"("payload" "jsonb") FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."decide_name_match"("payload" "jsonb") FROM "anon";
GRANT EXECUTE ON FUNCTION "public"."decide_name_match"("payload" "jsonb") TO "authenticated", "service_role";

-- fold_name() is a pure string function; every role may call it.
GRANT EXECUTE ON FUNCTION "public"."fold_name"("p" "text") TO "anon", "authenticated", "service_role";

INSERT INTO supabase_migrations.schema_migrations (version, name)
VALUES ('20260922120000', 'da0_3_name_match_reviews');

COMMIT;

-- Read-only verification after COMMIT (the editor shows this row).
SELECT sm.version, sm.name,
       to_regclass('public.name_match_reviews') IS NOT NULL                                   AS nmr_present,
       to_regprocedure('public.fold_name(text)') IS NOT NULL                                   AS fold_name_present,
       to_regprocedure('public.decide_name_match(jsonb)') IS NOT NULL                          AS decide_present,
       (SELECT count(*) FROM pg_attribute WHERE attrelid = 'public.workers'::regclass
          AND attname IN ('employer_name_raw','worksite_name_raw','names_import_id') AND NOT attisdropped) AS raw_columns
FROM supabase_migrations.schema_migrations sm WHERE sm.version = '20260922120000';
